name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      MAILOSAUR_BASE_URL: https://mailosaur.com/
      MAILOSAUR_SMTP_HOST: mailosaur.net
      MAILOSAUR_SMTP_PORT: 2525
      MAILOSAUR_API_KEY: ${{ secrets.MAILOSAUR_API_KEY }}
      MAILOSAUR_SERVER: ${{ secrets.MAILOSAUR_SERVER }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.0
    - name: Test
      run: go test -v

  build-next:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      MAILOSAUR_BASE_URL: https://next.mailosaur.com/
      MAILOSAUR_SMTP_HOST: mailosaur.email
      MAILOSAUR_SMTP_PORT: 2525
      MAILOSAUR_API_KEY: ${{ secrets.MAILOSAUR_API_KEY }}
      MAILOSAUR_SERVER: ${{ secrets.MAILOSAUR_SERVER }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.0
    - name: Test
      run: go test -v
